[package]
name = "account_data"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { workspace = true }
solana-program.workspace = true 
solana-system-interface = { workspace = true }

[features]
custom-heap = []
custom-panic = []


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }


[dev-dependencies]
litesvm = "0.9.1"
solana-instruction = "3.1.0"
solana-client =  "3.1.8"
solana-sdk = "3.0.0"
tokio = "1.49.0"


[[example]]
name = "client"
path = "../examples/client.rs"